/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package player_bidding.registration;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 
 * @author 01957
 */

public class Player_Registration11 extends javax.swing.JFrame {

    String PLAYER_CATEGORY;
     String url;
        int RUN,MATCH,AVG ,ID;
        String filename=null;
        byte[] person_image=null;
    /**
     * Creates new form Player_Registration
     */
    public Player_Registration11() throws ClassNotFoundException {
        initComponents();
        this.setVisible(true);
        this.setSize(1200,1000);
        this.setLocationRelativeTo(null);
       // show_user();
    }
     public ArrayList<User> userList() throws ClassNotFoundException{
        ArrayList<User> userList=new ArrayList<>(); 
         try {
            
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://SADDAMNVN:1433;databaseName=Player_bidding;integratedSecurity=true;";
            java.sql.Connection  con =DriverManager.getConnection(url);
         
            String query="select ID, NAME,CATEGORY,EMAIL,IMAGE,AVG_RUN,TOTAL_RUN from PLAYER_REGISTRATION";

            //String query="select NAME,DEPARTMENT_NAME,CATEGORY,PROPOSAL_PRICE,EMAIL,IMAGE,TOTAL_RUN,TOTAL_MATCH,TOTAL_WICKET,AVG_RUN,ID from PLAYER_REGISTRATION";
              Statement state=con.createStatement();
            ResultSet rs= state.executeQuery(query);
            User user;
            while(rs.next())
            {
               // System.out.println(rs.getInt("AVG_RUN"));
              user=new User(rs.getInt("ID"),rs.getString("NAME"),rs.getString("CATEGORY"),rs.getString("EMAIL"),rs.getBytes("IMAGE"),rs.getInt("AVG_RUN"),rs.getInt("TOTAL_RUN")); 
              //System.out.println(user);
           userList.add(user);
           //System.out.println(userList);
            }
           
            
        } catch (SQLException ex) {
            Logger.getLogger(PL_VIEWS.class.getName()).log(Level.SEVERE, null, ex);
        }
        return userList;
    }
   public void show_user() throws ClassNotFoundException 
   {
      ArrayList<User> list=userList();
      DefaultTableModel model=(DefaultTableModel) myTable.getModel();
     Object[]row =new Object[6];
     // System.out.println(list.size());
     for(int i=0;i<list.size();i++)
     {
       row[0]=list.get(i).getID();
       System.out.println(row[0]);
       row[1]=list.get(i).getNAME();
       row[2]=list.get(i).getCATEGORY();
       row[3]=list.get(i).getDEPARTMENT_NAME();
       row[4]=list.get(i).getPROPOSAL_PRICE();
       row[5]=list.get(i).getTOTAL_RUN();
         // System.out.println(row[3]);
       model.addRow(row);
     }
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Category = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        NAME = new javax.swing.JTextField();
        BATSMAN = new javax.swing.JRadioButton();
        ALL_ROUNDER = new javax.swing.JRadioButton();
        BOWLER = new javax.swing.JRadioButton();
        DEPARTMENT_NAME = new javax.swing.JTextField();
        PROPOSAL_PRICE = new javax.swing.JTextField();
        EMAIL = new javax.swing.JTextField();
        PASSWORD = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        IMAGE = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TOTAL_RUN = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TOTAL_MATCH = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TOTAL_WICKET = new javax.swing.JTextField();
        UPDATE = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        IMAGE_LABEL = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        myTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Player Registration");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(535, 535, 535)
                .addComponent(jLabel11)
                .addContainerGap(599, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1280, 70);

        jPanel4.setBackground(new java.awt.Color(102, 102, 255));

        jLabel4.setText("Name");

        jLabel5.setText("Department Name");

        jLabel6.setText("Category");

        jLabel7.setText("Proposal Price");

        jLabel8.setText("Email");

        jLabel9.setText("Password");

        NAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAMEActionPerformed(evt);
            }
        });

        Category.add(BATSMAN);
        BATSMAN.setText("Batsman");
        BATSMAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BATSMANActionPerformed(evt);
            }
        });

        Category.add(ALL_ROUNDER);
        ALL_ROUNDER.setText("All_Rounder");

        Category.add(BOWLER);
        BOWLER.setText("Bowler");
        BOWLER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOWLERActionPerformed(evt);
            }
        });

        PROPOSAL_PRICE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PROPOSAL_PRICEActionPerformed(evt);
            }
        });

        EMAIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EMAILActionPerformed(evt);
            }
        });

        PASSWORD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PASSWORDActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton14.setText("Sign");
        jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton14MouseClicked(evt);
            }
        });
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Image");

        IMAGE.setText("Select Image");
        IMAGE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IMAGEMouseClicked(evt);
            }
        });

        jLabel1.setText("Total Run");

        jLabel2.setText("Total Match");

        jLabel3.setText("Total Wicket");

        UPDATE.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        UPDATE.setText("Update");
        UPDATE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UPDATEMouseClicked(evt);
            }
        });

        delete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        delete.setText("Delete");
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });

        IMAGE_LABEL.setBackground(new java.awt.Color(0, 0, 255));

        myTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10"
            }
        ));
        jScrollPane1.setViewportView(myTable);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TOTAL_MATCH, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(BOWLER)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BATSMAN)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ALL_ROUNDER, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(TOTAL_RUN, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(NAME, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(DEPARTMENT_NAME, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(PROPOSAL_PRICE, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(EMAIL, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(PASSWORD, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(IMAGE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                        .addComponent(TOTAL_WICKET, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 899, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IMAGE_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(UPDATE)
                                .addGap(42, 42, 42)
                                .addComponent(delete)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(DEPARTMENT_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BOWLER)
                            .addComponent(BATSMAN)
                            .addComponent(ALL_ROUNDER)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PROPOSAL_PRICE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PASSWORD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(IMAGE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TOTAL_WICKET, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel1))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(TOTAL_RUN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(IMAGE_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(TOTAL_MATCH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton14)
                    .addComponent(UPDATE)
                    .addComponent(delete))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 70, 1280, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked

        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            url="jdbc:sqlserver://SADDAMNVN:1433;databaseName=Player_bidding;integratedSecurity=true;";
            java.sql.Connection  con =DriverManager.getConnection(url);
            int row=myTable.getSelectedRow();

            String value_id=myTable.getModel().getValueAt(row,0).toString();

            String query="DELETE FROM  PLAYER_REGISTRATION  WHERE   ID='"+value_id+"'";
            PreparedStatement pst=con.prepareStatement(query);

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"DEeleted SuccessFully");
            DefaultTableModel model=(DefaultTableModel) myTable.getModel();
            model.setRowCount(0);
            show_user();

            System.out.println("Connection created");

        }
        catch (Exception e) {
            System.out.println(e.toString());
            System.out.println("Sorry bro");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteMouseClicked

    private void UPDATEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UPDATEMouseClicked

        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            url="jdbc:sqlserver://SADDAMNVN:1433;databaseName=Player_bidding;integratedSecurity=true;";
            java.sql.Connection  con =DriverManager.getConnection(url);
            int row=myTable.getSelectedRow();

            String value_id=myTable.getModel().getValueAt(row,0).toString();

            String query="UPDATE  PLAYER_REGISTRATION SET NAME=?,DEPARTMENT_NAME=?,CATEGORY=?,PROPOSAL_PRICE=?,EMAIL=?,PASSWORD=?,IMAGE=?,TOTAL_RUN=?,TOTAL_MATCH=?,TOTAL_WICKET=?,AVG_RUN=? WHERE   ID='"+value_id+"'";
            //System.out.println(query+"found");
            // String query="select * from PLAYER_REGISTRATION";
            PreparedStatement pst=con.prepareStatement(query);
            pst.setString(1,NAME.getText());
            pst.setString(2,DEPARTMENT_NAME.getText());
            if(BOWLER.isSelected())
            {
                PLAYER_CATEGORY="Bowler";
            }
            else if(BATSMAN.isSelected()){
                PLAYER_CATEGORY="Batsman";
            }
            else
            {
                PLAYER_CATEGORY="All_Rounder";
            }

            pst.setString(3,PLAYER_CATEGORY);
            pst.setString(4,PROPOSAL_PRICE.getText());
            pst.setString(5,EMAIL.getText());
            String pass=String.valueOf(PASSWORD.getPassword());
            pst.setString(6,pass);
            pst.setString(7,IMAGE.getText());
            pst.setString(8,TOTAL_RUN.getText());
            pst.setString(9,TOTAL_MATCH.getText());
            pst.setString(10,TOTAL_WICKET.getText());

            RUN = Integer.parseInt(TOTAL_RUN.getText());
            MATCH = Integer.parseInt(TOTAL_MATCH.getText());
            AVG=RUN/MATCH;
            pst.setInt(11,AVG);

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Update SuccessFully");
            DefaultTableModel model=(DefaultTableModel) myTable.getModel();
            model.setRowCount(0);
            show_user();

            System.out.println("Connection created");

        }
        catch (Exception e) {
            System.out.println(e.toString());
            System.out.println("Sorry bro");
        }
    }//GEN-LAST:event_UPDATEMouseClicked

    private void IMAGEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IMAGEMouseClicked
        JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);
        File f=chooser.getSelectedFile();
        filename=f.getAbsolutePath();
        ImageIcon imageIcon=new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(IMAGE_LABEL.getWidth(),IMAGE_LABEL.getHeight(),Image.SCALE_SMOOTH));
        IMAGE_LABEL.setIcon(imageIcon);
        try{
            File image=new File(filename);
            FileInputStream fts=new  FileInputStream(image);
            ByteArrayOutputStream bos=new   ByteArrayOutputStream();
            byte[]buf=new byte[1024];
            for(int readNum;(readNum=fts.read(buf))!=-1;){
                bos.write(buf,0,readNum);
            }
            person_image=bos.toByteArray();

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }

        //IMAGE.setText(filename);

        // TODO add your handling code here:
    }//GEN-LAST:event_IMAGEMouseClicked

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MouseClicked

        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            url="jdbc:sqlserver://SADDAMNVN:1433;databaseName=Player_bidding;integratedSecurity=true;";
            java.sql.Connection  con =DriverManager.getConnection(url);
            String query="INSERT INTO PLAYER_REGISTRATION VALUES(?,?,?,?,?,?,?,?,?,?,?)";
            // String query="select * from PLAYER_REGISTRATION";
            PreparedStatement pst=con.prepareStatement(query);
            pst.setString(1,NAME.getText());
            pst.setString(2,DEPARTMENT_NAME.getText());
            if(BOWLER.isSelected())
            {
                PLAYER_CATEGORY="Bowler";
            }
            else if(BATSMAN.isSelected()){
                PLAYER_CATEGORY="Batsman";
            }
            else
            {
                PLAYER_CATEGORY="All_Rounder";
            }

            pst.setString(3,PLAYER_CATEGORY);
            pst.setString(4,PROPOSAL_PRICE.getText());
            pst.setString(5,EMAIL.getText());
            String pass=String.valueOf(PASSWORD.getPassword());
            pst.setString(6,pass);
            pst.setBytes(7,person_image);
            pst.setString(8,TOTAL_RUN.getText());
            pst.setString(9,TOTAL_MATCH.getText());
            pst.setString(10,TOTAL_WICKET.getText());

            RUN = Integer.parseInt(TOTAL_RUN.getText());
            MATCH = Integer.parseInt(TOTAL_MATCH.getText());
            AVG=RUN/MATCH;
            pst.setInt(11,AVG);
            // System.out.println(AVG);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Inserted SuccessFully");
            DefaultTableModel model=(DefaultTableModel) myTable.getModel();
            model.setRowCount(0);
            // show_user();

            System.out.println("Connection created");

        }
        catch (Exception e) {
            System.out.println(e.toString());
            System.out.println("Sorry bro");
        }
    }//GEN-LAST:event_jButton14MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PASSWORDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PASSWORDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PASSWORDActionPerformed

    private void EMAILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EMAILActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EMAILActionPerformed

    private void PROPOSAL_PRICEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PROPOSAL_PRICEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PROPOSAL_PRICEActionPerformed

    private void BOWLERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOWLERActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BOWLERActionPerformed

    private void BATSMANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BATSMANActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BATSMANActionPerformed

    private void NAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAMEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Player_Registration11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Player_Registration11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Player_Registration11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Player_Registration11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Player_Registration11().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Player_Registration11.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ALL_ROUNDER;
    private javax.swing.JRadioButton BATSMAN;
    private javax.swing.JRadioButton BOWLER;
    private javax.swing.ButtonGroup Category;
    private javax.swing.JTextField DEPARTMENT_NAME;
    private javax.swing.JTextField EMAIL;
    private javax.swing.JButton IMAGE;
    private javax.swing.JLabel IMAGE_LABEL;
    private javax.swing.JTextField NAME;
    private javax.swing.JPasswordField PASSWORD;
    private javax.swing.JTextField PROPOSAL_PRICE;
    private javax.swing.JTextField TOTAL_MATCH;
    private javax.swing.JTextField TOTAL_RUN;
    private javax.swing.JTextField TOTAL_WICKET;
    private javax.swing.JButton UPDATE;
    private javax.swing.JButton delete;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton14;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable myTable;
    // End of variables declaration//GEN-END:variables

   
}
