/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package player_bidding.registration;

import Bidding_folder.SOLDED_PLAYER;
import TeamOwner_folder.*;
import java.awt.Image;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import player_bidding.login.loginForm;

/**
 *
 * @author 01957
 */
public class PROFILE_VIEW extends javax.swing.JFrame {

   String total_match;
    /**
     * Creates new form Player_Registration
     */
    String pvemail,pvpass;
    public PROFILE_VIEW() {
        initComponents();
        this.setVisible(true);
        this.setSize(1200,1000);
        this.setLocationRelativeTo(null);
    }

    public void profile(String pvemail,String pvpass )
    {
        this.pvemail=pvemail;
        this.pvpass=pvpass;
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LOGOUT = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        profile = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        INPUT_NAME = new javax.swing.JTextField();
        PANEL = new javax.swing.JPanel();
        PICTURE = new javax.swing.JLabel();
        NAME = new javax.swing.JLabel();
        DEPARTMENT_NAME = new javax.swing.JLabel();
        CATEGORY = new javax.swing.JLabel();
        EMAIL = new javax.swing.JLabel();
        TOTAL_MATCH = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("PLAYERS PROFILE VIEW");

        LOGOUT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LOGOUT.setText("BACK");
        LOGOUT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LOGOUTMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(565, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(275, 275, 275)
                .addComponent(LOGOUT)
                .addGap(96, 96, 96))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(LOGOUT))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1280, 100);

        jPanel3.setBackground(new java.awt.Color(0, 204, 255));

        jPanel5.setBackground(new java.awt.Color(51, 255, 255));

        profile.setText("PROFILE");
        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileMouseClicked(evt);
            }
        });

        jLabel2.setText("NAME");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(INPUT_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 60, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(INPUT_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(profile)
                .addContainerGap(535, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 26, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 100, 320, 670);

        PANEL.setBackground(new java.awt.Color(102, 102, 255));

        NAME.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        DEPARTMENT_NAME.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        CATEGORY.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        EMAIL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        TOTAL_MATCH.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout PANELLayout = new javax.swing.GroupLayout(PANEL);
        PANEL.setLayout(PANELLayout);
        PANELLayout.setHorizontalGroup(
            PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANELLayout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addGroup(PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TOTAL_MATCH, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CATEGORY, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(PICTURE, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DEPARTMENT_NAME, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                            .addComponent(NAME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(433, Short.MAX_VALUE))
        );
        PANELLayout.setVerticalGroup(
            PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANELLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(PICTURE, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(NAME)
                .addGap(18, 18, 18)
                .addComponent(DEPARTMENT_NAME)
                .addGap(18, 18, 18)
                .addComponent(CATEGORY)
                .addGap(18, 18, 18)
                .addComponent(EMAIL)
                .addGap(18, 18, 18)
                .addComponent(TOTAL_MATCH)
                .addContainerGap(385, Short.MAX_VALUE))
        );

        getContentPane().add(PANEL);
        PANEL.setBounds(320, 100, 960, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents
//PROFILE SHOWING
    private void profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseClicked
     
         try {
          
         
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://SADDAMNVN:1433;databaseName=Player_bidding;integratedSecurity=true;";
            java.sql.Connection  con =DriverManager.getConnection(url);
           
            String querymax="select * from PLAYER_REGISTRATION WHERE NAME='"+INPUT_NAME.getText()+"' ";
           
            Statement state=con.createStatement();
            ResultSet rss= state.executeQuery(querymax);
            
            int id;
            while(rss.next())
            {
              
               NAME.setText("NAME :"+rss.getString("NAME"));
               DEPARTMENT_NAME.setText("DEPARTMENT NAME  :"+rss.getString("DEPARTMENT_NAME"));
               CATEGORY.setText("CATEGORY  :"+rss.getString("CATEGORY"));
               EMAIL.setText("EMAIL :"+rss.getString("EMAIL"));
               String s=String.valueOf(rss.getInt("TOTAL_MATCH"));
               TOTAL_MATCH.setText("TOTAL_MATCH :"+s);
               
               byte[]img=rss.getBytes("IMAGE");
               ImageIcon image=new ImageIcon(img);
               Image im=image.getImage();
              // Image myImg=im.getScaledInstance(50, 50,java.awt.Image.SCALE_SMOOTH);
               Image myImg=im.getScaledInstance(PICTURE.getWidth(),PICTURE.getHeight(),Image.SCALE_SMOOTH);

               //Image myImg=im.getScaledInstance(400,400,Image.SCALE_SMOOTH);
               ImageIcon newImage=new ImageIcon(myImg);
               PICTURE.setIcon(image);
               
               
            }
            
            //name check
             String querymaxC="select * from PLAYER_REGISTRATION WHERE NAME='"+INPUT_NAME.getText()+"' ";
           
            Statement stateC=con.createStatement();
            ResultSet rssC= stateC.executeQuery(querymax);
           if(rssC.next())
           {
               
           }
           else
           {
               JOptionPane.showMessageDialog(null,"Not Exit");
           }
            
           

           //show data in jTable
          
    
           
        }
        catch (Exception e) {
            System.out.println(e.toString());
            System.out.println("Sorry bro");
        }   
        
            
      INPUT_NAME.setText(null);
// TODO add your handling code here:
    }//GEN-LAST:event_profileMouseClicked

    private void LOGOUTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGOUTMouseClicked

LAST_PL_VIEWS LP=new LAST_PL_VIEWS();
 dispose();// TODO add your handling code here:
    }//GEN-LAST:event_LOGOUTMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
       
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PROFILE_VIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CATEGORY;
    private javax.swing.JLabel DEPARTMENT_NAME;
    private javax.swing.JLabel EMAIL;
    private javax.swing.JTextField INPUT_NAME;
    private javax.swing.JButton LOGOUT;
    private javax.swing.JLabel NAME;
    private javax.swing.JPanel PANEL;
    private javax.swing.JLabel PICTURE;
    private javax.swing.JLabel TOTAL_MATCH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton profile;
    // End of variables declaration//GEN-END:variables
}
