/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Home_folder;

import Bidding_folder.*;
import player_bidding.registration.*;
import TeamOwner_folder.*;
import java.awt.Image;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 01957
 */
public class All_Team_Home extends javax.swing.JFrame {

     String team_name,category1;
            int price=0,player_id,ss_MAX_PRICE=0,balancecheck,batsman,bowler;
            String s_team_name;
            int PROPOSAL_PRICE_INT;
            int exitteamcheckid;
  // String total_match;
    /**
     * Creates new form Player_Registration
     */
    String pvemail,pvpass;int selectorpage;
    public All_Team_Home() {
        initComponents();
        this.setVisible(true);
        this.setSize(1200,1000);
        this.setLocationRelativeTo(null);
      
        reamin();
    }         
        
    
    //SHOWING DATA IN TABLE
     public void reamin()
    {
         REMAINIST TL=new REMAINIST();
      ArrayList<REMAINIST.TEAMLIST> teamlist = TL.TEAMSEARCH();
      
       DefaultTableModel model=(DefaultTableModel) myTable1.getModel();
     Object[]row =new Object[7];
     // System.out.println(list.size());
     for(int i=0;i<teamlist.size();i++)
     {
       row[0]=teamlist.get(i).getTEAM_NAME();
       row[1]=teamlist.get(i).getNAME();
       row[2]=teamlist.get(i).getEMAIL();
       //remaining balance calculate
         exitteamchecking etc=new exitteamchecking();
        balancecheck=etc.balancechaking(teamlist.get(i).getTEAM_NAME(),89);
       row[3]=1000-balancecheck;
       //remaining batsman calculate
        batsman=etc.batsmanchaking(teamlist.get(i).getTEAM_NAME());
       row[4]=7-batsman;
       //remaining Bowler calculate
        bowler=etc.bowlerchaking(teamlist.get(i).getTEAM_NAME());
       row[5]=7-bowler;
        //remaining All_Rounder calculate
               int allrounder=etc.allrounderchaking(teamlist.get(i).getTEAM_NAME());
                row[6]=7-allrounder;
         // System.out.println(row[3]);
       model.addRow(row);
     }
      
    }
public void selectorpage( int checkhome){
    this.selectorpage=selectorpage;
}


   public void profile(String pvemail,String pvpass )
    {
        this.pvemail=pvemail;
        this.pvpass=pvpass;
    }
   /*
       public  PLAYER(String NAME,String DEPARTMENT_NAME,String CATEGORY ,int  PROPOSAL_PRICE,String EMAIL,byte[]IMAGE,int TOTAL_RUN,
    int TOTAL_MATCH ,int TOTAL_WICKET,int AVG_RUN  )
*/
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        myTable1 = new javax.swing.JTable();
        IMAGE = new javax.swing.JLabel();
        COACH_NAME = new javax.swing.JLabel();
        SELECTOR_LEVEL = new javax.swing.JLabel();
        coach_level = new javax.swing.JLabel();
        IMAGE1 = new javax.swing.JLabel();
        More_Info = new javax.swing.JButton();
        coach_img = new javax.swing.JLabel();
        COACH_NAME1 = new javax.swing.JLabel();
        abc = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        mytable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("All Team Information");

        jButton1.setText("BACK");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(398, 398, 398)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 461, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(114, 114, 114))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(42, 42, 42))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1280, 100);

        myTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Team Name", "Selector", "Selector Email", "Remain Balance", "Remain Batsman", "Remain Bowler", "Remain All_rounder"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(myTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 100, 850, 680);
        getContentPane().add(IMAGE);
        IMAGE.setBounds(1030, 180, 190, 120);
        getContentPane().add(COACH_NAME);
        COACH_NAME.setBounds(1040, 560, 230, 0);
        getContentPane().add(SELECTOR_LEVEL);
        SELECTOR_LEVEL.setBounds(1030, 140, 110, 20);
        getContentPane().add(coach_level);
        coach_level.setBounds(1030, 370, 120, 0);
        getContentPane().add(IMAGE1);
        IMAGE1.setBounds(1030, 420, 200, 110);

        More_Info.setText("More Information");
        More_Info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                More_InfoMouseClicked(evt);
            }
        });
        getContentPane().add(More_Info);
        More_Info.setBounds(1040, 110, 180, 23);
        getContentPane().add(coach_img);
        coach_img.setBounds(1050, 380, 140, 0);

        COACH_NAME1.setText(".");
        getContentPane().add(COACH_NAME1);
        COACH_NAME1.setBounds(1040, 560, 230, 40);

        abc.setText(".");
        getContentPane().add(abc);
        abc.setBounds(1050, 380, 200, 14);

        mytable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Solded Player Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(mytable1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(860, 140, 150, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       
        SL_VIEWS_ADMIN SAH=new  SL_VIEWS_ADMIN();
  dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked
 public void show_usersS() throws ClassNotFoundException
   {
      ArrayList<TEAMVIEW_HOME> list=playerList();
      DefaultTableModel model=(DefaultTableModel) mytable1.getModel();
     Object[]row =new Object[1];
     //     public SOLDED(int ID, String NAME, String EMAIL, String CATEGORY, String DEPARTMENT_NAME, String TEAM_NAME, int PRICE) {

     for(int i=0;i<list.size();i++)
     {
       row[0]=list.get(i).getNAME();
       
       model.addRow(row);
     }
   }

  //ADING DATA IN ARRAYLIST
   public ArrayList<TEAMVIEW_HOME> playerList(){
       
       ArrayList<TEAMVIEW_HOME>  playerList=new ArrayList<>();
       try {
          
         
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://SADDAMNVN:1433;databaseName=Player_bidding;integratedSecurity=true;";
            java.sql.Connection  con =DriverManager.getConnection(url);
           
            String querymax=" SELECT  P.ID,P.NAME,P.EMAIL,P.CATEGORY,P.DEPARTMENT_NAME,B.TEAM_NAME,B.PRICE FROM PLAYER_REGISTRATION P ,BIDDING_TABLE B where P.ID = B.PLAYER_ID AND B.TEAM_NAME='"+s_team_name+"'";
            Statement state=con.createStatement();
            ResultSet rrr= state.executeQuery(querymax);
            TEAMVIEW_HOME player;
          boolean ff=false;
          while(rrr.next()){
              ff=true;
              player=new TEAMVIEW_HOME(rrr.getString("NAME"),rrr.getString("EMAIL"),rrr.getString("CATEGORY"),rrr.getString("DEPARTMENT_NAME"),rrr.getInt("PRICE"));
          playerList.add(player);
          }
if(ff==false)
{
    JOptionPane.showMessageDialog(null,"PLAYER IS UNSOLDED"); 
}
    
          
           

        }
        catch (Exception e) {
            System.out.println(e.toString());
            System.out.println("Sorry bro");
        } 
       return playerList;
       
   }

    
    private void More_InfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_More_InfoMouseClicked
        //reset button
                    IMAGE1.setIcon(null);
                    abc.setText(null);
                    COACH_NAME1.setText(null);
         
                    
            int row=myTable1.getSelectedRow();
             s_team_name=myTable1.getModel().getValueAt(row,0).toString();
            String selector_name=myTable1.getModel().getValueAt(row,1).toString();
            System.out.println(s_team_name);
             try {
          
         
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://SADDAMNVN:1433;databaseName=Player_bidding;integratedSecurity=true;";
            java.sql.Connection  con =DriverManager.getConnection(url);
           //SELECTOR INFO RETRIEVE
            String querymax="select * from SELECTOR_REGISTRATION WHERE TEAM_NAME='"+s_team_name+"' AND NAME='"+selector_name+"' ";
            Statement state=con.createStatement();
            ResultSet rrr= state.executeQuery(querymax);
           
          
          while(rrr.next()){
                     byte [] img = rrr.getBytes("IMAGE");
                    //Resize The ImageIcon
                    ImageIcon image = new ImageIcon(img);
                    Image im = image.getImage();
                    Image myImg = im.getScaledInstance(IMAGE.getWidth(), IMAGE.getHeight(),Image.SCALE_SMOOTH);
                    ImageIcon newImage = new ImageIcon(myImg);
                   IMAGE.setIcon(newImage);
                   SELECTOR_LEVEL.setText("Selector Image");
                  
          }
       //SELECTOR INFO RETRIEVE
            String querymaxc="select * from COACH_REGISTRATION WHERE TEAM_NAME='"+s_team_name+"'";
            Statement stateE=con.createStatement();
            ResultSet rrrE= stateE.executeQuery(querymaxc);
           
          
          while(rrrE.next()){
              System.out.println("pppp");
                     byte [] img1 = rrrE.getBytes("IMAGE");
                    //Resize The ImageIcon
                    ImageIcon image = new ImageIcon(img1);
                    Image im1 = image.getImage();
                    Image myImg1 = im1.getScaledInstance(IMAGE1.getWidth(), IMAGE1.getHeight(),Image.SCALE_SMOOTH);
                    ImageIcon newImage1 = new ImageIcon(myImg1);
                   IMAGE1.setIcon(newImage1);
                    abc.setText("Coach Image");
                    COACH_NAME1.setText("Coach Name :"+rrrE.getString("NAME"));
                    
                   
          }
       
            playerList();
             DefaultTableModel model=(DefaultTableModel) mytable1.getModel();
            model.setRowCount(0);
             show_usersS();
    
            System.out.println("Connection created");

        }
        catch (Exception e) {
            System.out.println(e.toString());
            System.out.println("Sorry bro");
        } 
// TODO add your handling code here:

    }//GEN-LAST:event_More_InfoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new All_Team_Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel COACH_NAME;
    private javax.swing.JLabel COACH_NAME1;
    private javax.swing.JLabel IMAGE;
    private javax.swing.JLabel IMAGE1;
    private javax.swing.JButton More_Info;
    private javax.swing.JLabel SELECTOR_LEVEL;
    private javax.swing.JLabel abc;
    private javax.swing.JLabel coach_img;
    private javax.swing.JLabel coach_level;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable myTable1;
    private javax.swing.JTable mytable1;
    // End of variables declaration//GEN-END:variables
}
